/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import contentmodel from "../assets/contentlast.gltf"

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF(contentmodel)
  return (
    <group ref={group} {...props} dispose={null} scale={0.3}
    onClick={() => props.switchSmile()}>
      <mesh
        geometry={nodes.text.geometry}
        material={materials['Material.001']}
        position={[-0.19, 8, -0.02]}
        rotation={[1.57, 0, 0]}>
        <mesh
          geometry={nodes.Cube.geometry}
          material={materials['Material.002']}
          position={[-0.79, -0.99, 0.81]}
          rotation={[-1.57, 0, 0]}
        />
      </mesh>
    </group>
  )
}

useGLTF.preload(contentmodel)
