/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import contentbutton from "../assets/contentbutton.glb"

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF(contentbutton)
  return (
    <group ref={group} {...props} dispose={null} 
    onClick={() => props.switchSmile()}>
      <group position={[-0.19, 2.6, -0.02]} rotation={[1.57, 0, 0]} scale={0.5}>
        <mesh geometry={nodes.Content.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Content_1.geometry} material={materials['Material.002']} />
      </group>
    </group>
  )
}

useGLTF.preload(contentbutton)
