/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import switchmodel from "../assets/newswitched.gltf"

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(switchmodel)
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    if (props.first === true)
    {
      actions["Action.001"].repetitions = 1;
      actions["Action.001"].clampWhenFinished = true;
      actions["Action.001"].reset().fadeIn(0.15).play();
      actions["Action.001"].syncWith(actions["Second.003"]).syncWith(actions["Third.002"]).syncWith(actions["Fourth.002"])
    } else actions["Action.001"].fadeOut();

    if (props.second === true)
    {
      actions["Second.003"].repetitions = 1;
      actions["Second.003"].clampWhenFinished = true;
      actions["Second.003"].reset().fadeIn(0.15).play();
      actions["Second.003"].syncWith(actions["Action.001"]).syncWith(actions["Third.002"]).syncWith(actions["Fourth.002"])
    } else actions["Second.003"].fadeOut();

    if (props.third === true)
    {
      actions["Third.002"].repetitions = 1;
      actions["Third.002"].clampWhenFinished = true;
      actions["Third.002"].reset().fadeIn(0.15).play();
      actions["Third.002"].syncWith(actions["Action.001"]).syncWith(actions["Second.003"]).syncWith(actions["Fourth.002"])
    } else actions["Third.002"].fadeOut();

    if (props.fourth === true)
    {
      actions["Fourth.002"].repetitions = 1;
      actions["Fourth.002"].clampWhenFinished = true;
      actions["Fourth.002"].reset().fadeIn(0.15).play();
      actions["Fourth.002"].syncWith(actions["Action.001"]).syncWith(actions["Second.003"]).syncWith(actions["Third.002"])
    } else actions["Fourth.002"].fadeOut();


  })



  return (
    <group ref={group} {...props} dispose={null} scale={0.2}  
    rotation={[0, 4.7, 0]} position={[-0.9, -1.8, 0]}>
      <mesh onClick={() => props.firstSwitch()}
        geometry={nodes.Torus.geometry}
        material={nodes.Torus.material}
        position={[0, 0, 2]}
        rotation={[0, 0, -Math.PI / 2]}
      />
      <mesh onClick={() => props.firstSwitch()}
        geometry={nodes.Torus001.geometry}
        material={materials.Material}
        position={[0, 0, 2]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.7}
      />
      <mesh geometry={nodes.Cube.geometry} material={materials['Material.003']} position={[-1.05, 0, 0]} />
      <mesh onClick={() => props.secondSwitch()}
        geometry={nodes.Torus002.geometry}
        material={nodes.Torus002.material}
        position={[0, 0, -2.21]}
        rotation={[0, 0, -Math.PI / 2]}
      />
      <mesh onClick={() => props.secondSwitch()}
        geometry={nodes.Torus003.geometry}
        material={nodes.Torus003.material}
        position={[0, 0, -2.21]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.7}
      />
      <mesh onClick={() => props.thirdSwitch()}
        geometry={nodes.Torus004.geometry}
        material={nodes.Torus004.material}
        position={[0, 0, -6.64]}
        rotation={[0, 0, -Math.PI / 2]}
      />
      <mesh onClick={() => props.thirdSwitch()}
        geometry={nodes.Torus005.geometry}
        material={nodes.Torus005.material}
        position={[0, 0, -6.64]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.7}
      />
      <mesh onClick={() => props.fourthSwitch()}
        geometry={nodes.Torus006.geometry}
        material={nodes.Torus006.material}
        position={[0, 0, -11.15]}
        rotation={[0, 0, -Math.PI / 2]}
      />
      <mesh onClick={() => props.fourthSwitch()}
        geometry={nodes.Torus007.geometry}
        material={nodes.Torus007.material}
        position={[0, 0, -11.15]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.7}
      />
      <group position={[0.58, -2.79, 2.98]} scale={0.67}>
        <mesh geometry={nodes.Cube_1.geometry} material={nodes.Cube_1.material} />
        <mesh geometry={nodes.Cube_2.geometry} material={nodes.Cube_2.material} />
      </group>
      <mesh
        geometry={nodes.Text.geometry}
        material={nodes.Text.material}
        position={[0.05, -2.92, 3.12]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.49}
      />
      <group position={[0.58, -2.79, -1.27]} scale={0.67}>
        <mesh geometry={nodes.Cube002_1.geometry} material={nodes.Cube002_1.material} />
        <mesh geometry={nodes.Cube002_2.geometry} material={nodes.Cube002_2.material} />
      </group>
      <mesh
        geometry={nodes.Text001.geometry}
        material={nodes.Text001.material}
        position={[0.05, -2.92, -1.53]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.49}
      />
      <group position={[0.58, -2.79, -5.78]} scale={0.67}>
        <mesh geometry={nodes.Cube003_1.geometry} material={nodes.Cube003_1.material} />
        <mesh geometry={nodes.Cube003_2.geometry} material={nodes.Cube003_2.material} />
      </group>
      <mesh
        geometry={nodes.Text002.geometry}
        material={nodes.Text002.material}
        position={[0.05, -2.92, -5.63]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.49}
      />
      <group position={[0.58, -2.79, -10.27]} scale={0.67}>
        <mesh geometry={nodes.Cube004_1.geometry} material={nodes.Cube004_1.material} />
        <mesh geometry={nodes.Cube004_2.geometry} material={nodes.Cube004_2.material} />
      </group>
      <mesh
        geometry={nodes.Text003.geometry}
        material={nodes.Text003.material}
        position={[0.05, -2.92, -10.49]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.49}
      />
      <mesh onClick={() => props.firstSwitch()}
        name="Sphere"
        geometry={nodes.Sphere.geometry}
        material={nodes.Sphere.material}
        position={[-0.05, -0.05, 2]}
        rotation={[0, 0, -0.76]}
        scale={0.63}>
        <mesh onClick={() => props.firstSwitch()}
          geometry={nodes.Cylinder.geometry}
          material={nodes.Cylinder.material}
          position={[1.73, -0.01, 0]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={0.3}
        />
      </mesh>
      <mesh onClick={() => props.secondSwitch()}
        name="Sphere001"
        geometry={nodes.Sphere001.geometry}
        material={nodes.Sphere001.material}
        position={[-0.05, -0.05, -2.22]}
        rotation={[0, 0, -0.76]}
        scale={0.63}>
        <mesh onClick={() => props.secondSwitch()}
          geometry={nodes.Cylinder001.geometry}
          material={nodes.Cylinder001.material}
          position={[1.73, -0.01, 0]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={0.3}
        />
      </mesh>
      <mesh onClick={() => props.thirdSwitch()}
        name="Sphere002"
        geometry={nodes.Sphere002.geometry}
        material={nodes.Sphere002.material}
        position={[-0.05, -0.05, -6.64]}
        rotation={[0, 0, -0.76]}
        scale={0.63}>
        <mesh onClick={() => props.thirdSwitch()}
          geometry={nodes.Cylinder002.geometry}
          material={nodes.Cylinder002.material}
          position={[1.73, -0.01, 0]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={0.3}
        />
      </mesh>
      <mesh
        name="Sphere003" onClick={() => props.fourthSwitch()}
        geometry={nodes.Sphere003.geometry}
        material={nodes.Sphere003.material}
        position={[-0.05, -0.05, -11.17]}
        rotation={[0, 0, -0.76]}
        scale={0.63}>
        <mesh onClick={() => props.fourthSwitch()}
          geometry={nodes.Cylinder003.geometry}
          material={nodes.Cylinder003.material}
          position={[1.73, -0.01, 0]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={0.3}
        />
      </mesh>
    </group>
  )
}

useGLTF.preload(switchmodel)
