/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import othermodel from "./react3dlogo.gltf"

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(othermodel)
  const { actions } = useAnimations(animations, group)


  useEffect(() => {
    console.log(actions)
    actions.turn.play()
  })

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        name="Curve002"
          geometry={nodes.Curve002.geometry}
        material={materials['SVGMat.003']}
        position={[5, 2, 0]}
        rotation={[0, 2, 1.6]}
        scale={7}
      />
    </group>
  )
}

useGLTF.preload(othermodel)
