/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import thismodel from "./gltfexport.gltf"

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF(thismodel)
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, 0, 0]}>
        <mesh geometry={nodes.FaceBuilderHead_mesh.geometry} material={materials.kt_facebuilder_material} />
        <mesh geometry={nodes.FaceBuilderHead_mesh_1.geometry} material={materials['Material.003']}  />
      </group>
    </group>
  )
}

useGLTF.preload(thismodel)
