/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import jsmodel from "./jslogo.gltf"

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(jsmodel)
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    console.log(actions)
    actions.CurveAction.play()
  })



  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
      
        name="Curve"
        geometry={nodes.Curve.geometry}
        
        position={[1.2, 1.5, 0]}
        rotation={[1.57, 0, 1.56]}
        scale={3}
        color={"yellow"}
      />
    </group>
  )
}

useGLTF.preload(jsmodel)
