/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import medkit from "../src/medkit.gltf"

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF(medkit)
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[2.38, 2.03, -0.82]} scale={[0.45, 1, 1]}>
        <pointLight intensity={1} decay={2} color="#c7dbff" rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <group position={[-2.31, 2.03, -0.82]} scale={[0.45, 1, 1]}>
        <pointLight intensity={1} decay={2} color="#caddff" rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <group position={[0, -2.5, -0.2]} scale={4.3} rotation={[0, 0.8, 0]} >
        <mesh  geometry={nodes.Плоскость004_1.geometry} material={materials.Med_Kit} />
      </group>
    </group>
  )
}

useGLTF.preload(medkit)
