/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import nodelogo from "./nodelogo.gltf"


export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(nodelogo)
  const { actions } = useAnimations(animations, group)
  useEffect(() => {
    console.log(actions)
    actions.CurveAction.play()
  })

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        name="Curve"
        geometry={nodes.Curve.geometry}
        material={materials['SVGMat.001']}
        position={[1.3, 1.6, 1]}
        // rotation={[1.57, 0, 1.56]}
        scale={7}
      />
    </group>
  )
}

useGLTF.preload(nodelogo)
