/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import othermodel from "./react3dlogo.gltf"


export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(othermodel)
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    console.log(actions)
    actions.turn.play()
  })


  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        name="Curve"
        geometry={nodes.Curve.geometry}
        material={materials['SVGMat.006']}
        position={[2, 5, 0]}
        rotation={[0, 0, 0]}
    
      />
    </group>
  )
}

useGLTF.preload(othermodel)
